# Generated by Django 4.2.7 on 2024-10-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedlessons',
            options={'verbose_name_plural': 'Completed Lessons'},
        ),
    ]
