# Generated by Django 4.2.7 on 2024-10-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cartorderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
