# Generated by Django 4.2.7 on 2024-10-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_teachers_cartorder_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='api.cartorder'),
        ),
    ]
