# Generated by Django 4.2.7 on 2024-10-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cartorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.coupon'),
        ),
    ]
