# Generated by Django 4.2.7 on 2024-10-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cartorderitem_coupons_cartorderitem_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
