# Generated by Django 4.2.7 on 2024-10-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cartorder_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='initial_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
