# Generated by Django 4.2.7 on 2024-10-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cartorderitem_initial_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='sub_total',
        ),
    ]
