# Generated by Django 4.2.7 on 2024-11-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_course_teacher_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
