# Generated by Django 4.2.7 on 2024-11-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_variantitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
